[package]
name = "rusty-gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.15.0"
eframe = "0.27.2"
egui = "0.27.2"
rand = "0.9.0-alpha.1"
time = "0.3.36"

[profile.dev]
overflow-checks = true
